#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
admin=$3
user_pwd=$4
forumtitle=$5

# Check if admin exists
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong admin"
    exit 1
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a esotalk
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Vérifie que le mot de passe n'est pas vide.
if [[ -z $user_pwd ]]; then
	echo "Mot de passe incorrect"
	exit 1
fi

# Retrieve admin email
admin_email=$(sudo yunohost user info $admin | grep mail: | sed "s/mail: //g")

# Add settings to YunoHost
sudo yunohost app setting esotalk admin -v $admin
sudo yunohost app setting esotalk domain -v $domain

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'esotalk' as database name and user
db_user=esotalk

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting esotalk mysqlpwd -v $db_pwd

# Copy files to right place
final_path=/var/www/esotalk
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/esotalk.conf

# Change variables in esotalk configuration
sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/esotalk.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" /etc/nginx/conf.d/$domain.d/esotalk.conf

# Files owned by root, www-data can just read
sudo mkdir $final_path/cache
sudo mkdir $final_path/config
sudo mkdir $final_path/uploads
sudo mkdir $final_path/uploads/avatars
sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755
sudo chown -R root: $final_path
# www-data can write on plugins and cache
sudo chown -R www-data $final_path

sudo yunohost app ssowatconf
sudo service nginx reload

# esotalk installation via curl
#curl -k --data "forumTitle=$forumtitle&baseURL=$domain$path/&friendlyURLs=1&mysqlHost=localhost&mysqlUser=$db_user&mysqlPass=$db_pwd&mysqlDB=$db_user&tablePrefix=et&adminUser=$admin&adminEmail=$admin_email&adminPass=$user_pwd&adminConfirm=$user_pwd" https://$domain$path/?p=install/info?submit > /dev/null
